 export const LOAD_ROUTES_SUCCESS = 'LOAD_ROUTES_SUCCESS';
 export const LOAD_DIRECTIONS_SUCCESS = 'LOAD_DIRECTIONS_SUCCESS';
 export const LOAD_STOPS_SUCCESS = 'LOAD_STOPS_SUCCESS';
 export const LOAD_TRIPS_SUCCESS = 'LOAD_TRIP_SUCCESS';
 export const SAVE_ROUTE_SUCCESS = 'SAVE_ROUTE_SUCCESS';
 export const SAVE_DIRECTION_SUCCESS = 'SAVE_DIRECTION_SUCCESS';
 export const SAVE_STOP_SUCCESS = 'SAVE_STOP_SUCCESS';